### ISSUE TITLE
Add SharPersist

### ISSUE THREAD

**Issue by y0k4i-1337** [Flangvik/SharpCollection#10]
Any chance to include https://github.com/fireeye/SharPersist in the list?

**Comment by Flangvik** [comment]
Actually it's there, was just missing from the readme, will add it! https://github.com/Flangvik/SharpCollection/blob/master/NetFramework_4.7_Any/SharPersist.exe

**Comment by leebaird** [comment]
Was just going to ask the same thing! Suggest updating the README when you get back from Vegas. haha
