### ISSUE TITLE
Add SharpSQLPwn

### ISSUE THREAD

**Issue by lefayjey** [Flangvik/SharpCollection#14]
Hello,
A shameless plug here: 
Would you consider adding SharpSQLPwn: https://github.com/lefayjey/SharpSQLPwn ?
Thanks!

**Comment by Flangvik** [comment]
Yup, will add. Thanks

**Comment by lefayjey** [comment]
Thank you! 
Another interesting and similar project I found that you could also consider:
https://github.com/mlcsec/SharpSQL
