### ISSUE TITLE
SharpHound Repositories

### ISSUE THREAD

**Issue by Zamanry** [Flangvik/SharpCollection#17]
Based on the last compile date in your repository, I think you are using the SharpHound from [here](https://github.com/BloodHoundAD/SharpHound3) rather than from the supported version [here](https://github.com/BloodHoundAD/SharpHound). Could you update pipeline to use the supported version?

Love the repository, keep it up!!

**Comment by Zamanry** [comment]
Appears resolved. Closing.
![image](https://user-images.githubusercontent.com/28152647/179052912-b4054ce0-3876-4373-97a9-5d7dfe0494da.png)

**Comment by Zamanry** [comment]
Appears to be an issue again: Updated 8 days ago in the SharpHound repo and updated 2 months ago in SharpCollection. I noticed their branch name keeps changing which maybe is breaking things?
- https://github.com/BloodHoundAD/SharpHound

**Comment by Flangvik** [comment]
@Zamanry might be the case, i'll look into this once i get back from DefCON

**Comment by Zamanry** [comment]
> @Zamanry might be the case, i'll look into this once i get back from DefCON

Good luck on the presentation!

**Comment by Flangvik** [comment]
Fixed, my Azure pipeline looked at changes to the old main branch, switched to dev. Thanks for letting me know! :)
