### ISSUE TITLE
Add a few tools

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [Flangvik/SharpCollection#2]
https://github.com/V1V1/SharpScribbles - I don't see anything like StickyNotesExtract in the repo, and this implementation of "ThunderFox" seems to work really well
https://github.com/djhohnstein/SharpWeb - This is supposed to dump stuff from all the web browsers but it doesnt seem to work? Maybe it works on older versions of Chrome... Just putting this out there.
https://github.com/0xthirteen/SharpRDP - Remote Desktop Protocol Console Application for Authenticated Command Execution

**Comment by Flangvik** [comment]
Hey @Marshall-Hallenbeck, il look into adding SharpRDP and SharpScribbles. Any other C# based tools that are missing / you come over, let me know! Thanks for contributing :)

**Comment by Flangvik** [comment]
All added, closing this now 👍
