### ISSUE TITLE
Request to Add GMSAPasswordReader

### ISSUE THREAD

**Issue by juliourena** [Flangvik/SharpCollection#24]
:) Thanks for your contributions @Flangvik we love SharpCollection.

Can you add GMSAPasswordReader?

https://github.com/rvazarkar/GMSAPasswordReader

**Comment by Flangvik** [comment]
Thanks for the suggestion @juliourena, i'll look into adding this!

**Comment by Flangvik** [comment]
This has been added to the pipeline and will appear in the github repo soon, closing!
