### ISSUE TITLE
Add ShadowSpray

### ISSUE THREAD

**Issue by Zamanry** [Flangvik/SharpCollection#26]
https://github.com/ShorSec/ShadowSpray

**Comment by Zamanry** [comment]
Closing, Whisker is already here which is "essentially" the same. Closing:
- https://github.com/eladshamir/Whisker

**Comment by Zamanry** [comment]
Coming back to this, I realized that Whisker is for manipulation based on gained rights, while ShadowSpray is for password spraying. Although they are similar, they are different in usage. Reopening...

**Comment by Flangvik** [comment]
Added!
