### ISSUE TITLE
SharpSCCM Not Working

### ISSUE THREAD

**Issue by Zamanry** [Flangvik/SharpCollection#28]
I tested SharpSCCM on two non-domain joined Windows 10 systems (with Defender disabled) and was unable to get the tool working:

![image](https://github.com/Flangvik/SharpCollection/assets/28152647/9245337d-2b98-478d-a4e2-8cadb3d3812d)

![MicrosoftTeams-image](https://github.com/Flangvik/SharpCollection/assets/28152647/0ee203a9-e77d-4ae2-9cbb-268cfcc2325c)

**Comment by Flangvik** [comment]
Thanks for the request, I'll be looking at this soon ™
