### ISSUE TITLE
Add GodPotato

### ISSUE THREAD

**Issue by Ari-Weinberg** [Flangvik/SharpCollection#29]
Any chance you can add GodPotato: https://github.com/BeichenDream/GodPotato
Thanks so much!

**Comment by Flangvik** [comment]
Thanks for the request, I'll be looking at this and possibly adding this soon ™

**Comment by Flangvik** [comment]
Might add at an later stage, however pre-compiled binaries are in the release section for this repo.

**Comment by n3rada** [comment]
Pre-compilled but not up-to-date ones! Your repo is gold for this.
