### ISSUE TITLE
Change SQLClient

### ISSUE THREAD

**Issue by daniel2005d** [Flangvik/SharpCollection#30]
Could you update the current SQLClient project by this one https://github.com/daniel2005d/SQLClient/tree/main, as the current version lacks support.

I'm the creator of a new SQLClient program, and in the future, I will be adding more functionalities

**Comment by Flangvik** [comment]
Thanks for the request, I'll be looking at this soon ™

**Comment by Flangvik** [comment]
Sorry, i will not be adding this.
