### ISSUE TITLE
[New Bin] Add SharpTokenFinder

### ISSUE THREAD

**Issue by HuskyHacks** [Flangvik/SharpCollection#31]
Hello!

I have reimplemented [TokenFinder](https://github.com/doredry/TokenFinder) in C# so now we can pwn Office Desktop Apps with impunity from the comfort of a reflective assembly! Would love to see it pulled into this repo.

https://github.com/HuskyHacks/SharpTokenFinder

![image](https://github.com/Flangvik/SharpCollection/assets/57866415/61fc224d-8039-4515-88ca-aa3a9babb5fb)

The current build is for .NET 4.5 but I don't see any issue bumping it to 4.7 as well.

Thank you!

**Comment by Flangvik** [comment]
Thanks for the request, I'll be looking at this and possibly adding this soon ™

**Comment by Flangvik** [comment]
Added!
