### ISSUE TITLE
[New Bin Request] - SharpFinder

### ISSUE THREAD

**Issue by Syrkadian** [Flangvik/SharpCollection#33]
SharpFinder is a C# tool for enumerating files matching specific criteria on readable shares within an Active Directory domain. It is inspired by @harmj0uy's [Find-InterestingFile](https://powersploit.readthedocs.io/en/latest/Recon/Find-InterestingFile/) cmdlet, which is part of [PowerSploit](https://github.com/PowerShellMafia/PowerSploit).

https://github.com/s0lst1c3/SharpFinder

**Comment by Flangvik** [comment]
Thanks for the request, I'll be looking at this and possibly adding this soon ™

**Comment by Flangvik** [comment]
Added
