### ISSUE TITLE
Inveigh Out of Date and Name Changed

### ISSUE THREAD

**Issue by gjhami** [Flangvik/SharpCollection#34]
It looks like the current version of Inveigh in SharpCollection is 0.913 which doesn't support several of the flags in the latest version, v2.0.10, such as `-LLMNRTypes` and specifying an IPv6 AAAA record with `-DNSTypes`.

Also, for the SharpCollection readme: InveighZero is now just called Inveigh, since the main version of the tool is now the C# version previously called InveighZero.

https://github.com/Kevin-Robertson/Inveigh

Thanks so much for making a great tool, I use it all the time!

**Comment by Flangvik** [comment]
Thanks for the feedback and info, I'll be looking at this soon ™

**Comment by Flangvik** [comment]
So the current Inveigh project is .NET 6.0 ++, not NetFramework, therefor i cannot add this.
