### ISSUE TITLE
Access to pipeline source code

### ISSUE THREAD

**Issue by maik-s** [Flangvik/SharpCollection#37]
First of all thanks for the effort put into this project!

As you state in the readme, the pipeline should be visible on the given link 

> The pipeline can be found here: https://dev.azure.com/FlangvikDev/SharpRelease

However, when accessing the link - even with authentication - it is not possible to review the pipeline runner's code.
Clicking through all the items does not give me the runner config.

![image](https://github.com/Flangvik/SharpCollection/assets/5398731/6148e4d8-2345-46a4-8b33-fc8433886674)

I guess it is a configuration mistake, that the yml file is not publicly readable - please review your settings.

Kind regards.

**Comment by Flangvik** [comment]
Pipelines are found at: https://dev.azure.com/FlangvikDev/SharpRelease/_build

However, I am unsure if the actual source code for the Pipelines is viewable by "anyone". Might look into that at some point.
